[package]
name = "linear_algebra"
version = "0.1.0"
edition = "2021"

[features]
# Defines a feature named `webp` that does not enable any other features.
#cuda = ["cublas-sys"]
cuda = ["cublas-sys", "cuda-runtime-sys"]

[dependencies]
#cublas = { version = "0.2.0", optional =true }
#cuda-sys = { version = "0.2.0", optional =true }
#cuda-driver-sys = { version = "0.3.0", optional =true }
cuda-runtime-sys = {version="0.3.0-alpha.1", optional=true}
cublas-sys = { version = "0.1.0", optional =true }
