[package]
name = "cusolver-sys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
anyhow = "1.0.31"
cc = "1.0"
fs_extra = "~1.2.0"
ftp = "3.0"
zip = "0.5"
